Reverted opentracing-util to 0.31.0 and jaeger-client to 0.33.1 because protocol buffers 2.5.0 doesn't seem to support TEXT_MAP_INJECT (introduced in opentracing-util 0.32.0). This leads to DN connection failure to NN during startup:
2019-05-03 22:55:43,504 WARN datanode.DataNode: Problem connecting to server: localhost/127.0.0.1:9999
java.io.IOException: com.google.protobuf.ServiceException: io.jaegertracing.internal.exceptions.UnsupportedFormatException: Builtin.TEXT_MAP_INJECT
	at org.apache.hadoop.ipc.ProtobufHelper.getRemoteException(ProtobufHelper.java:47)
	at org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolClientSideTranslatorPB.versionRequest(DatanodeProtocolClientSideTranslatorPB.java:292)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.retrieveNamespaceInfo(BPServiceActor.java:239)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.connectToNNAndHandshake(BPServiceActor.java:287)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.run(BPServiceActor.java:849)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.ServiceException: io.jaegertracing.internal.exceptions.UnsupportedFormatException: Builtin.TEXT_MAP_INJECT
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:241)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:119)
	at com.sun.proxy.$Proxy18.versionRequest(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolClientSideTranslatorPB.versionRequest(DatanodeProtocolClientSideTranslatorPB.java:289)
	... 4 more
Caused by: io.jaegertracing.internal.exceptions.UnsupportedFormatException: Builtin.TEXT_MAP_INJECT
	at io.jaegertracing.internal.JaegerTracer.inject(JaegerTracer.java:205)
	at io.opentracing.util.GlobalTracer.inject(GlobalTracer.java:199)
	at org.apache.hadoop.tracing.TraceUtils.spanContextToByteString(TraceUtils.java:139)
	at org.apache.hadoop.util.ProtoUtil.makeRpcRequestHeader(ProtoUtil.java:185)
	at org.apache.hadoop.util.ProtoUtil.makeRpcRequestHeader(ProtoUtil.java:171)
	at org.apache.hadoop.ipc.Client$Connection.<init>(Client.java:469)
	at org.apache.hadoop.ipc.Client.lambda$getConnection$1(Client.java:1609)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1608)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.Client.call(Client.java:1394)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	... 7 more